# Change these first
owner: Sumit-SC # Your GitHub organization or username, where this repository lives
repo: uptime-webapp # The name of this repository

sites:
  - name: Portfolio Page
    url: sumit-sc.github.io
    icon: https://cdnl.iconscout.com/lottie/premium/preview-watermark/portfolio-animation-gif-download-5220633.mp4
  - name: Portfolio Website
    url: https://sumit.indevs.in
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /uptime-webapp
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sumit's Service Status
  introTitle: "**Service Status** for my web applications, powered by Upptime and a status page, powered entirely by GitHub."
  introMessage: This page monitors the uptime and response time of my portfolio and core services.  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Advanced monitoring frequency (optional)
# commitMessages:
# readmeTick: ":green_heart: Update uptime [skip ci]"

# Add this at the bottom
notifications:
  - type: telegram
