# Change these first
owner: Sumit-SC # Your GitHub organization or username, where this repository lives
repo: ping # The name of this repository

# Add this section to change the frequency
workflow-schedule:
  uptime: "*/15 * * * *"
  
sites:
  - name: Portfolio Page
    url: sumit-sc.github.io
    icon: https://i.ibb.co/yF29Pd46/icon.png
  - name: Portfolio Website
    url: https://sumit.indevs.in
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /ping
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  # name: "Sumit's Portfolio<br />Service Status"
  name: |
    Sumit's Portfolio
    Service Status
  introTitle: "**Service Status** for my web applications, powered by Upptime and a status page, powered entirely by GitHub."
  introMessage: This page monitors the uptime and response time of my portfolio and core services.  
  navbar:
    - title: Portfolio Website
      href: /
    - title: Server Stats
      href: http://telemetry.indevs.in
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
    - title: Upp-time 
      # sub: Build your own website tracker
      href: https://upptime.js.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Advanced monitoring frequency (optional)
# commitMessages:
# readmeTick: ":green_heart: Update uptime [skip ci]"

# Add this at the bottom
# notifications:
#   - type: telegram
notifications:
  - type: telegram
    # # If the secret-only method fails, you can try this format
    # chatId: -1002414692810 
    # messageThreadId: 1976
