name: Latency Spike Alerts

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  latency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Analyze latency
        id: analyze
        run: |
          FILE="history/summary.json"
          ALERTS=""

          COUNT=$(jq length "$FILE")

          for i in $(seq 0 $(($COUNT - 1))); do
            NAME=$(jq -r ".[$i].name" "$FILE")
            STATUS=$(jq -r ".[$i].status" "$FILE")
            SLUG=$(jq -r ".[$i].slug" "$FILE")

            [ "$STATUS" != "up" ] && continue

            YML_FILE="history/$SLUG.yml"
            [ ! -f "$YML_FILE" ] && continue

            CURRENT=$(grep 'responseTime:' "$YML_FILE" | awk '{print $2}')

            # ===== Simple Spike Logic =====
            if [ "$CURRENT" -gt 1500 ]; then

              ALERTS+="🚨 High Latency Detected\n"
              ALERTS+="🌐 $NAME\n"
              ALERTS+="⚡ $CURRENT ms\n"
              ALERTS+="🔗 https://status.sumit.indevs.in/history/$SLUG\n\n"

            fi

          done

          if [ -n "$ALERTS" ]; then
            echo "alert=true" >> $GITHUB_OUTPUT
            echo "msg<<EOF" >> $GITHUB_OUTPUT
            echo -e "$ALERTS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "alert=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram
        if: steps.analyze.outputs.alert == 'true'
        run: |
          MESSAGE="${{ steps.analyze.outputs.msg }}\n🕒 $(TZ='Asia/Kolkata' date +"%d %b %Y | %I:%M %p IST")"

          PAYLOAD=$(jq -n \
            --arg chat_id "${{ secrets.CHAT_ID }}" \
            --arg text "$MESSAGE" \
            --argjson thread_id ${{ secrets.ALERTS_TOPIC_ID }} \
            '{
              chat_id: $chat_id,
              message_thread_id: $thread_id,
              text: $text,
              disable_web_page_preview: true
            }')

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.SUMMARY_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
